yarnPath: .yarn/releases/yarn-sources.js
enableTransparentWorkspaces: false

packageExtensions:
  browser-resolve@*:
    dependencies:
      resolve: ^1.12.0
  debug@*:
    dependencies:
      supports-color: ^7.1.0
